{
 "title": "Redis demo dashboard 2",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "GET /api/users/probabilistic/random",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "uri" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_server_requests_seconds",
     "query": "SELECT non_negative_derivative(mean(\"count\"), 10s) FROM \"http_server_requests_seconds\" WHERE (\"uri\" = '/api/users/probabilistic/random' AND \"method\" = 'GET') AND $timeFilter GROUP BY time($__interval), \"uri\", \"method\", \"status\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "uri",
       "operator": "=",
       "value": "/api/users/probabilistic/random"
      },
      { "condition": "AND", "key": "method", "operator": "=", "value": "GET" }
     ]
    }
   ]
  },
  {
   "title": "Redis key space hits",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "replication_role" ], "type": "tag" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "redis",
     "query": "SELECT non_negative_derivative(mean(\"keyspace_hits\"), 10s) FROM \"redis\" WHERE $timeFilter GROUP BY time($__interval), \"server\", \"replication_role\", \"status\" fill(null)",
     "select": [
      [
       { "params": [ "keyspace_hits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Redis key space miss",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "replication_role" ], "type": "tag" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "redis",
     "query": "SELECT non_negative_derivative(mean(\"keyspace_hits\"), 10s) FROM \"redis\" WHERE $timeFilter GROUP BY time($__interval), \"server\", \"replication_role\", \"status\" fill(null)",
     "select": [
      [
       { "params": [ "keyspace_misses" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Database HIT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "users_db_hit_count_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recomputed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "recomputed_cache_count_total",
     "query": "SELECT non_negative_derivative(mean(\"evicted_keys\"), 10s) FROM \"redis\" WHERE $timeFilter GROUP BY time($__interval), \"server\", \"replication_role\" fill(null)",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Expired keys",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "replication_role" ], "type": "tag" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "redis",
     "query": "SELECT non_negative_derivative(mean(\"keyspace_hits\"), 10s) FROM \"redis\" WHERE $timeFilter GROUP BY time($__interval), \"server\", \"replication_role\", \"status\" fill(null)",
     "select": [
      [
       { "params": [ "expired_keys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  }
 ]
}